config/routes.rb
Rails.application.routes.draw do
    root to: 'books#index'
    
    # 家計簿データ
    get "/books", to: "books#index"
    # 新規作成
    post "/books", to: "books#create"
    get "/books/new", to: "books#new", as: "new_book"
    get "/books/:id/edit", to: "books#edit", as: "edit_book"
    get "/books/:id", to: "books#show", as: "book"
    # 更新
    patch "/books/:id", to: "books#update"
    # 削除
    delete "/books/:id", to: "books#destroy"
    
    # 会員登録
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    
    # 会員ログイン
    get "/login", to: "session#new"
    post "/login", to: "session#create"
    
    # 会員ログアウト
    get "/logout", to: "session#destroy"
    
    # 会員編集
    get "/users/edit", to: "users#edit", as: "edit_user"
    patch "/users", to: "users#update", as: "user"
    
    # routeの自動生成
    # resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    
    # モデルのデータを関連付ける
    # belongs_to :user
    
    validates :year, presence: true
    validates :month, presence: true
    validates :inout, presence: true
    validates :category, presence: true
    validates :amount, presence: true
    
end

app/models/user.rb
class User < ApplicationRecord
    # パスワードを安全に保存するための記述
    has_secure_password
    
    # モデルのデータを関連づける
    # has_many :books
    
    # バリデーション
    validates :name, presence: true, length: {maximum: 20}
    validates :email, presence: true, uniqueness: true, length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    # ログインしていない場合ログイン画面にリダイレクト
    def redirect_to_login
        redirect_to login_path if session[:user_id].blank?
    end
    
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    
    # 事前実行
    before_action :set_book, only: [:show, :edit, :update, :destroy]
    before_action :redirect_to_login
    
    
    
    def index
       @books = Book.where(user_id: session[:user_id])
       @books = @books.where(year: params[:year]) if params[:year].present?
       @books = @books.where(month: params[:month]) if params[:month].present?
    end
    
    def show
        set_book
    end
    
    def new
        @book = Book.new
    end
    
    def create
        book_params = params.require(:book).permit(:year, :month, :inout, :category, :amount)
        book_params[:user_id] = session[:user_id]
        # 新しいインスタンスの生成
        @book = Book.new(book_params)
        if @book.save
            flash[:notice] = "家計簿に" + @book.year.to_s + "年" + @book.month.to_s + "月" + @book.category + "のデータを登録しました"
            # 一覧画面へのリダイレクト
            redirect_to books_path
        else
            flash.now[:alert] = "登録に失敗しました"
            render :new
        end
        
    end
    
    def edit
        set_book
    end
    
    def update
        set_book
        book_params
        if @book.update(book_params)
            flash[:notice] = "データを更新しました"
            # 詳細画面へのリダイレクト
            redirect_to book_path
        else
            flash.now[:alert] = "データの更新に失敗しました"
            render :edit
        end
    end
    
    def destroy
        set_book
        @book.destroy
        flash[:notice] = "データを削除しました"
        redirect_to books_path
    end
    

    
    # このコントローラー内でしか使わないメソッド
    private
    
    def set_book
        @book = Book.where(user_id: session[:user_id]).find(params[:id])
    end
    

    def book_params
        # 該当データの検索
        book_params = params.require(:book).permit(:year, :month, :inout, :category, :amount)
    end
    
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
    
    before_action :redirect_to_books, only: [:new, :create]
    
    
    def new
        
    end
    
    # ログイン
    def create
        user = User.find_by(email: params[:email])
        # userが存在し、パスワードが一致した場合
        if user.present? && user.authenticate(params[:password])
            flash[:notice] = "ログインに成功しました"
            session[:user_id] = user.id
            redirect_to books_path
        else
            flash.now[:alert] = "ログインに失敗しました"
            render "new"
        end
    end
    
    # ログアウト
    def destroy
        session[:user_id] = nil
        redirect_to login_path
    end
    
    private
    
    # 家計簿一覧画面へのリダイレクト
    def redirect_to_books
        redirect_to books_path if session[:user_id].present?
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    before_action :redirect_to_login, only:[:edit, :update]
    
    def new
        @user = User.new
    end
    
    def create
        user_params = params.require(:user).permit(:name, :email, :password, :password_confirmation)
        @user = User.new(user_params)
        if @user.save
            flash[:notice] = "登録しました"
            # ログイン画面にリダイレクト
            redirect_to login_path
        else
           flash.now[:alert] = "登録に失敗しました"
           render "new"
        end
    end
    
    def edit
        @user = User.find(session[:user_id])
    end
    
    def update
       @user = User.find(session[:user_id])
       user_params = params.require(:user).permit(:name, :email)
       if @user.update(user_params)
           flash[:notice] = "更新しました"
           redirect_to edit_user_path(@user)
       else
            flash.now[:alert] = "更新に失敗しました"
            render "edit"
       end

    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<h1>家計簿<%= type %></h1>

<%= form_with(model: @book, local: true, method: method) do |f| %>
    <div class="form-group">
        <%= f.label :year, "年度" %>
        <%= f.number_field :year, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :month, "月" %>
        <%= f.number_field :month, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :inout, "収支" %>
        <%= f.select :inout, [["収入", 1], ["支出", 2]], {}, {class: "form-control"} %>
    </div>
    <div class="form-group">
        <%= f.label :category, "カテゴリー" %>
        <%= f.text_field :category, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :amount, "金額" %>
        <%= f.number_field :amount, class: "form-control" %>
    </div>
    
    <%= link_to "戻る", books_path, class: "btn btn-secondary" %>
    <%= f.submit type, class: "btn btn-primary" %>
<% end %>

app/views/books/edit.html.erb
<%= render partial: "form", locals: {type: "更新", method: "patch"} %>

app/views/books/index.html.erb
<h1>家計簿一覧</h1>

<div class="card" style="margin-bottom: 20px;">
    <div class="card-body">
        <p>検索</p>
        <%= form_with method: "get", local: true do |f| %>
        <div class="form-row">
          <div class="col">
            <%= f.number_field :year, placeholder: "年度を入力", class: "form-control" %>
          </div>
          <div class="col">
            <%= f.number_field :month, placeholder: "対象月を入力", class: "form-control" %>
          </div>
          <div class="col">
            <%= f.submit "検索", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
</div>

<%= link_to "新規登録", new_book_path, class: "btn btn-success" %>
<table class="table table-striped" style="margin-top: 20px;">
    <tr>
        <th>年月</th>
        <th>収支</th>
        <th>カテゴリー</th>
        <th>金額</th>
        <th>リンク</th>
    </tr>
    <% sum = 0 %>
    <% income = 0 %>
    <% expense = 0 %>
    <% @books.each do |book| %>
    <tr>
        <td><%= book.year %>年<%= book.month %>月</td>
        <td>
            <% if book.inout == 1 %>
            収入
            <% else %>
            支出
            <% end %>
        </td>
        <td><%= book.category %></td>
        <td><%= book.amount %>万円</td>
        <td>
            <%= link_to "詳細", book_path(book), class: "btn btn-info" %> 
            <%= link_to "編集", edit_book_path(book), class: "btn btn-warning" %>
            <%= link_to "削除", book_path(book), method: "delete", data: {confirm: "本当に削除しますか？"}, class: "btn btn-danger" %>
        </td>
    </tr>
    <!--収入合計の算出-->
    <% if book.inout == 1 %>
        <% income += book.amount %>
    <% end %>
    <!--支出合計の算出-->
    <% if book.inout == 2 %>
        <% expense += book.amount %>
    <% end %>
    <!--残額の算出-->
    <% if book.inout == 1 %>
        <% sum += book.amount %>
    <% else %>
        <% sum -= book.amount %>
    <% end %>
    <% end %>
    <tr>
        <td></td>
        <td></td>
        <td>収入合計</td>
        <td><%= income %>万円</td>
        <td></td>
    </tr>
     <tr>
        <td></td>
        <td></td>
        <td>支出合計</td>
        <td><%= expense %>万円</td>
        <td></td>
    </tr>
     <tr>
        <td></td>
        <td></td>
        <td>残額</td>
        <td><%= sum %>万円</td>
        <td></td>
    </tr>
</table>

app/views/books/new.html.erb
<%= render partial: "form", locals: {type: "登録", method: nil} %>

app/views/books/show.html.erb
<h1>家計簿詳細</h1>
<table class="table table-striped table-hover">
    <tr>
        <th>年月</th>
        <td><%= @book.year %>年<%= @book.month %>月</td>
    </tr>
    <tr>
        <th>収支</th>
        <td>
            <% if @book.inout == 1 %>
            収入
            <% else %>
            支出
            <% end %>
        </td>
    </tr>
    <tr>
        <th>カテゴリー</th>
        <td><%= @book.category %></td>
    </tr>
    <tr>
        <th>金額</th>
        <td><%= @book.amount %></td>
    </tr>
</table>
<%= link_to "戻る", books_path, class: "btn btn-secondary" %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KakeiboApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-light bg-light">
      <div>
        <%= link_to "家計簿アプリ", "/", class: "navbar-brand" %>
      </div>
      <div>
        <!-- ログインしている場合 -->
        <% if session[:user_id].present? %>
        <%= link_to "会員内容の変更", edit_user_path, class: "btn btn-outline-info" %>
          <%= link_to "ログアウト", logout_path, class: "btn btn-outline-secondary" %>
        <% else %>
          <%= link_to "会員登録", signup_path, class: "btn btn-outline-primary" %>
        <% end %>
      </div>
    </nav>
    
    
    <div class="container">
      <!--フラッシュメッセージの表示-->
    <% if flash[:notice] %>
      <div class="alert alert-success" role="alert">
        <%= flash[:notice] %>
      </div>
    <% end %>
    
    <% if flash[:alert] %>
      <div class="alert alert-danger" role="alert">
        <%= flash[:alert] %>
      </div>
    <% end %>
    
    <%= yield %>
    </div>
  </body>
  
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</html>

app/views/session/new.html.erb
<h1>ログイン</h1>
<%= form_with(url: login_path, local: true) do |f| %>

    <div class="form-group">
        <%= f.label :email, "メールアドレス" %>
        <%= f.text_field :email, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :password, "パスワード" %>
        <%= f.password_field :password, class: "form-control" %>
    </div>
    
    <%= f.submit "ログイン", class: "btn btn-primary" %>
    
<% end %>

app/views/users/edit.html.erb
<h1>会員情報更新</h1>
<%= form_with(model: @user, url: user_path, method: "patch", local: true) do |f| %>

    <div class="form-group">
        <%= f.label :name, "名前" %>
        <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :email, "メールアドレス" %>
        <%= f.text_field :email, class: "form-control" %>
    </div>
   
   <%= f.submit "更新", class: "btn btn-primary" %>

<% end %>

app/views/users/new.html.erb
<h1>会員登録</h1>
<%= form_with(model: @user, url: signup_path, local: true )do |f| %>

    <div class="form-group">
        <%= f.label :name, "名前" %>
        <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :email, "メールアドレス" %>
        <%= f.text_field :email, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :password, "パスワード" %>
        <%= f.password_field :password, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :password_comfirmation, "パスワード確認用" %>
        <%= f.password_field :password_comfirmation, class: "form-control" %>
    </div>
    <%= f.submit "登録", class: "btn btn-primary" %>

<% end %>